routes/web.php
<?php


use App\User;

Auth::routes();
Route::get('/', 'HomeController@index')->name('dashboard');

// user
Route::get('/user','UserController@index');
Route::get('/user/add',['as'=>'user.add','uses'=>'UserController@create']);
Route::post('/user/create',['as'=>'user.create','uses'=>'UserController@store']);
Route::get('/user/delete/{id}',['as'=>'user.delete','uses'=>'UserController@destroy']);
Route::get('/user/edit/{id}',['as'=>'user.edit','uses'=>'UserController@edit']);
Route::put('/user/update/{id}',['as'=>'user.update','uses'=>'UserController@update']);
//end user





// Resourceful Route
Route::resource('employee' ,'EmployeeController');
Route::resource('employee-expense' ,'EmployeeExpenseController');
Route::resource('attendance' ,'AttendanceController');


// Routes for Ajax Call
Route::get('all_employee','EmployeeController@AllEmployee');
Route::get('all_employee_expense','EmployeeExpenseController@AllEmployeeExpense');
Route::get('all_attendance','AttendanceController@AllAttendance');

//Products Route
Route::resource('product', 'ProductController');
//Sales Route
Route::resource('sale', 'SalesController');
Route::post('/import', 'SalesController@import');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ProductController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $products = Product::all();
        return view('products.index', compact("products"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'product_name' => 'required',
            'product_details' => 'required',
            'product_sku_code' => 'numeric|required',
            'product_price' => 'numeric|required',
        ]);


        $product = Product::create([
            'product_name' => $request->product_name,
            'product_details' => $request->product_details,
            'product_sku_code' => $request->product_sku_code,
            'product_price' => $request->product_price,
        ]);
        if ($product) {
            $request->session()->flash('msg', 'Product added Successfully!');
            return redirect()->route('product.index');
        } else{
            return redirect()->back();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $id = $product;
        $product = Product::findOrFail($id)->first();
        if($product){
            return view('products.edit')->with('product' , $product);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {   
        $request->validate([
            'product_name' => 'required',
            'product_details' => 'required',
            'product_sku_code' => 'numeric|required',
            'product_price' => 'numeric|required',
        ]);

        $id = $product;
        $find_product = Product::findOrFail($id)->first();

        $product = $find_product->update([
            'product_name' => $request->product_name,
            'product_details' => $request->product_details,
            'product_sku_code' => $request->product_sku_code,
            'product_price' => $request->product_price,
        ]);

        if ($product) {
            $request->session()->flash('msg', 'Product\'s Information Update Successfully!');
            return redirect()->route('product.index');
        } else{
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product = Product::find($product)->first();
        $product->delete();
        return "Product deleted Successfully!";
    }
}

resources/views/products/add.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<div class="box-header with-border">
						<legend class="box-title" style="text-align: center; font-weight: bold;">Add New Product</legend>
					</div>
				</div>
				<div class="col-md-3"></div>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ route('product.store') }}">
				@csrf
				<div class="box-body">
					
					<!-- name -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_name') ? ' has-error' : '' }}">
								<label for="product_name">Product Name :</label>
								<input type="text" name="product_name" value="{{ old('product_name') }}" class="form-control" placeholder="Enter Name" required="">
								@if ($errors->has('product_name'))
								<span class="help-block">
									<strong>{{ $errors->first('product_name') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>				
					</div>
					
					<!-- details -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_details') ? ' has-error' : '' }}">
								<label for="product_details">Product Details :</label>
								<input type="text" name="product_details" value="{{ old('product_details') }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_details'))
								<span class="help-block">
									<strong>{{ $errors->first('product_details') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
					<!-- sku code -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_sku_code') ? ' has-error' : '' }}">
								<label for="product_sku_code">Product SKU Code :</label>
								<input type="text" name="product_sku_code" value="{{ old('product_sku_code') }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_sku_code'))
								<span class="help-block">
									<strong>{{ $errors->first('product_sku_code') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
					<!-- price -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_price') ? ' has-error' : '' }}">
								<label for="product_price">Product Price :</label>
								<input type="text" name="product_price" value="{{ old('product_price') }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_price'))
								<span class="help-block">
									<strong>{{ $errors->first('product_price') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<button type="submit" class="btn btn-primary col-sm-12">Submit</button>
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<div class="box-header with-border">
						<legend class="box-title" style="text-align: center; font-weight: bold;">Edit Product</legend>
					</div>
				</div>
				<div class="col-md-3"></div>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ route('product.update',['product' => $product->id]) }}">
				@method('PUT')
				@csrf
				<div class="box-body">
					
					<!-- name -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_name') ? ' has-error' : '' }}">
								<label for="product_name">Product Name :</label>
								<input type="text" name="product_name" value="{{ $product->product_name }}" class="form-control" placeholder="Enter Name" required="">
								@if ($errors->has('product_name'))
								<span class="help-block">
									<strong>{{ $errors->first('product_name') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>				
					</div>
					
					<!-- details -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_details') ? ' has-error' : '' }}">
								<label for="product_details">Product Details :</label>
								<input type="text" name="product_details" value="{{ $product->product_details }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_details'))
								<span class="help-block">
									<strong>{{ $errors->first('product_details') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
					<!-- sku code -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_sku_code') ? ' has-error' : '' }}">
								<label for="product_sku_code">Product SKU Code :</label>
								<input type="text" name="product_sku_code" value="{{ $product->product_sku_code }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_sku_code'))
								<span class="help-block">
									<strong>{{ $errors->first('product_sku_code') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
					<!-- price -->
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<div class="form-group col-sm-12 {{ $errors->has('product_price') ? ' has-error' : '' }}">
								<label for="product_price">Product Price :</label>
								<input type="text" name="product_price" value="{{ $product->product_price }}" class="form-control" placeholder="Enter Details" required="">
								@if ($errors->has('product_price'))
								<span class="help-block">
									<strong>{{ $errors->first('product_price') }}</strong>
								</span>
								@endif
							</div>
						</div>
						<div class="col-md-3"></div>
					</div>
					
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<div class="row">
						<div class="col-md-3"></div>
						<div class="col-md-6">
							<button type="submit" class="btn btn-primary col-sm-12">Update</button>
						</div>
						<div class="col-md-3"></div>
					</div>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">All Products</h3>
        <a href="{{ route('product.create') }}" class="text-right btn btn-success"><i class="fa fa-users fa-fw"></i> Add Product</a>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example1_info">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>SKU Code</th>
                            <th>Product Name</th>
                            <th>Details</th>
                            <th>Product Price</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                            
                    <tbody>
                        @foreach($products as $product)
	                        <tr>

	                            <td>{{ $product->id }}</td>
	                            <td>{{ $product->product_sku_code }}</td>
	                            <td>{{ $product->product_name }}</td>
	                            <td>{{ $product->product_details }}</td>
	                            <td>{{ $product->product_price }}</td>
	                            <td>
	                                <a href="{{ route('product.edit',['product' => $product->id]) }}" class="btn btn-warning">
	                                    <i class="fa fa-edit"></i> 
	                                </a>
	                                
	                                <a href="javascript;" class="btn btn-danger" @click.prevent="deleteProduct({{ $product->id }})">
	                                    <i class="fa fa-trash"></i> 
	                                </a>
	                            </td>
	            
	                        </tr>
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>

@endsection