routes/web.php
<?php


use App\User;

Auth::routes();
Route::get('/', 'HomeController@index')->name('dashboard');

// user
Route::get('/user','UserController@index');
Route::get('/user/add',['as'=>'user.add','uses'=>'UserController@create']);
Route::post('/user/create',['as'=>'user.create','uses'=>'UserController@store']);
Route::get('/user/delete/{id}',['as'=>'user.delete','uses'=>'UserController@destroy']);
Route::get('/user/edit/{id}',['as'=>'user.edit','uses'=>'UserController@edit']);
Route::put('/user/update/{id}',['as'=>'user.update','uses'=>'UserController@update']);
//end user





// Resourceful Route
Route::resource('employee' ,'EmployeeController');
Route::resource('employee-expense' ,'EmployeeExpenseController');
Route::resource('attendance' ,'AttendanceController');


// Routes for Ajax Call
Route::get('all_employee','EmployeeController@AllEmployee');
Route::get('all_employee_expense','EmployeeExpenseController@AllEmployeeExpense');
Route::get('all_attendance','AttendanceController@AllAttendance');

//Products Route
Route::resource('product', 'ProductController');
//Sales Route
Route::resource('sale', 'SalesController');
Route::post('/import', 'SalesController@import');

resources/views/includes/default_js.blade.php
<!--======================================= Common js STARTS =====================================-->

<!-- jQuery 3 -->
<script src="{{asset('bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- App js -->
<script src="{{asset('js/app.js')}}"></script>
<!-- Morris.js charts -->
<script src="{{asset('bower_components/raphael/raphael.min.js')}}"></script>
<script src="{{asset('bower_components/morris.js/morris.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{asset('bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('bower_components/jquery-knob/dist/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{asset('bower_components/moment/min/moment.min.js')}}"></script>
<script src="{{asset('bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('bower_components/fastclick/lib/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('dist/js/demo.js')}}"></script>

<!-- DataTables -->
<script src="{{asset('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

</script>

<script type="text/javascript">
    $("#example1").DataTable();
	$("#example2").DataTable();
	$('.datepicker').datepicker({
    	autoclose: true
    });
    $(".alert.notify").fadeIn(2000,function(){
    	setTimeout(function() {
    		$(".alert.notify").fadeOut(1000);    		
    	}, 5000);
    });
    $('ul.nav-tabs li a').click(function(){
    	$('.tab-pane').removeClass('show');
    });
</script>



<!--======================================= Common js ENDS =======================================-->

resources/views/includes/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Copyright &copy;DMS </strong> All rights reserved.
  </footer>

resources/views/includes/header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>DMS</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>DMS</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ asset('img/profile.png') }}" class="user-image" alt="User Image">
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
          </a>
                  

          <ul class="dropdown-menu" style="border: 1px solid #3c8dbc;">
            <!-- User image -->
            <li class="user-header">

              <img src="{{ asset('img/profile.png') }}" class="img-circle" alt="User Image">

              <p>
                {{ Auth::user()->name }} - {{ Auth::user()->designation }}
                <small>Member since {{ substr(Auth::user()->created_at,0,10) }}</small>
              </p>
            </li>
            
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-primary btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="javascript;" class="btn btn-primary btn-flat" @click.prevent='logOut'>Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/includes/html_head.blade.php
<!--========================HTML HEAD STARTS========================-->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>DMS | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta name="csrf-token" content="{{ csrf_token() }}">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('bower_components/font-awesome/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('bower_components/Ionicons/css/ionicons.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('dist/css/AdminLTE.min.css')}}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset('dist/css/skins/_all-skins.min.css')}}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{asset('bower_components/morris.js/morris.css')}}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{asset('bower_components/jvectormap/jquery-jvectormap.css')}}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  @yield('stylesheets')
<!--========================HTML HEAD ENDS========================-->

resources/views/includes/main_menu.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('img/profile.png') }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>

    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN MENU</li>
      <li class="active treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>

      <li class="treeview">
          <a href="#">
              <i class="fa fa-users"></i> <span>Employee</span>
              <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu" style="display: none;">
              <li>
                  <a href="{{ route('employee.create') }}"><i class="fa fa-circle-o"></i>Add Employee</a>
              </li>
              <li>
                  <a href="{{ route('employee.index') }}"><i class="fa fa-circle-o"></i>Employee List</a>
              </li>
              <li>
                  <a href="{{ route('employee-expense.index') }}"><i class="fa fa-circle-o"></i>Employee Expense</a>
              </li>
          </ul>
      </li>

      <li class="treeview">
          <a href="#">
            <i class="fa fa-user"></i>
            <span>Users</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{url('/user/add')}}"><i class="fa fa-circle-o"></i> Add User</a></li>
            <li><a href="{{url('/user')}}"><i class="fa fa-circle-o"></i> Users List</a></li>
          </ul>

      </li>

        <!-- start Product  -->
        <li class="treeview">
            <a href="#">
              <i class="fa fa-product-hunt"></i>
              <span>Products</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{ route('product.create') }}"><i class="fa fa-circle-o"></i> Add Product </a></li>
              <li><a href="{{ route('product.index') }}"><i class="fa fa-circle-o"></i> Products List </a></li>
            </ul>
        </li>
        <!-- end Product -->

        <!-- start Sales  -->
        <li class="treeview">
            <a href="#">
              <i class="fa fa-shopping-cart"></i>
              <span>Sales</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
            </a>
            <ul class="treeview-menu">
              <li><a href="{{ route('sale.create') }}"><i class="fa fa-circle-o"></i> Add Sales </a></li>
              <li><a href="{{ route('sale.index') }}"><i class="fa fa-circle-o"></i> Sales List </a></li>
            </ul>
        </li>
        <!-- end Sales -->

      <li class="treeview">
          <a href="#">
            <i class="fa fa-book"></i>
            <span>Attendance</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('attendance.create')}}"><i class="fa fa-circle-o"></i> Take Attendance</a></li>
            <li><a href="{{ route('attendance.index')}}"><i class="fa fa-circle-o"></i> Attendance list</a></li>
          </ul>
      </li>
     
    </ul>
  </section>
  <!-- /.sidebar -->

</aside>