routes/web.php
<?php


use App\User;

Auth::routes();
Route::get('/', 'HomeController@index')->name('dashboard');

// user
Route::get('/user','UserController@index');
Route::get('/user/add',['as'=>'user.add','uses'=>'UserController@create']);
Route::post('/user/create',['as'=>'user.create','uses'=>'UserController@store']);
Route::get('/user/delete/{id}',['as'=>'user.delete','uses'=>'UserController@destroy']);
Route::get('/user/edit/{id}',['as'=>'user.edit','uses'=>'UserController@edit']);
Route::put('/user/update/{id}',['as'=>'user.update','uses'=>'UserController@update']);
//end user





// Resourceful Route
Route::resource('employee' ,'EmployeeController');
Route::resource('employee-expense' ,'EmployeeExpenseController');
Route::resource('attendance' ,'AttendanceController');


// Routes for Ajax Call
Route::get('all_employee','EmployeeController@AllEmployee');
Route::get('all_employee_expense','EmployeeExpenseController@AllEmployeeExpense');
Route::get('all_attendance','AttendanceController@AllAttendance');

//Products Route
Route::resource('product', 'ProductController');
//Sales Route
Route::resource('sale', 'SalesController');
Route::post('/import', 'SalesController@import');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $guarded = [];

    public function employee_expense()
    {
        return $this->hasOne('App\EmployeeExpense');
    }
    public function attendance()
    {
        return $this->hasMany('App\Attendance');
    }
    public function count_absent()
    {
        return $this->hasOne('App\Attendance')->selectRaw("count(*) as count,employee_id")->groupBy('employee_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function AllEmployee()
    {
        $employees = Employee::all();
        return response()->json($employees);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['employees'] = Employee::all();
        return view('employees.employee-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all() ,[
            'name' => 'string|required|max:255',
            'email' => 'required|email|unique:employees',
            'phone' => 'required|regex:/(01)[0-9]{9}/|unique:employees',
            'gender' => 'required',
            'dob' => 'required|date',
            'present_addr' => 'required',
            'permanent_addr' => 'required',
            'department' => 'required',
            'designation' => 'required',
            'join_date' => 'required',
            'joining_salary' => 'required',
            'salary' => 'required',
            'photo' => 'sometimes|image',
            'father_name' => 'sometimes|string',
        ]);

        if ($validator->fails()) {
            $request->session()->flash('err', 'Please check the highlighted inputs!');
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('app');
        }


        $employee = Employee::create([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'dob' => date('Y-m-d', strtotime($request->dob)),
            'present_addr' => $request->present_addr,
            'permanent_addr' => $request->permanent_addr,
            'department' => $request->department,
            'designation' => $request->designation,
            'join_date' => date('Y-m-d', strtotime($request->join_date)),
            'joining_salary' => $request->joining_salary,
            'salary' => $request->salary,
            'father_name' => $request->father_name,
            'photo' => $photo ?? null
        ]);
        if ($employee) {
            $request->session()->flash('msg', 'Employee Created Successfully!');
            return redirect()->route('employee.index');
        } else{
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        $id = $employee;
        $data['employee'] = Employee::findOrFail($id)->first();
        return view('employees.profile',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $id = $employee;
        $employee = Employee::findOrFail($id)->first();
        if($employee){
            return view('employees.edit')->with('employee' , $employee);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $id = $employee;
        $f_employee = Employee::findOrFail($id)->first();

        $validator = Validator::make($request->all() ,[
            'name' => 'string|required|max:255',
            'email' => 'required|email|unique:employees,email,'.$f_employee->id,
            'phone' => 'required|regex:/(01)[0-9]{9}/|unique:employees,phone,'.$f_employee->id,
            'gender' => 'required',
            'dob' => 'required|date',
            'present_addr' => 'required',
            'permanent_addr' => 'required',
            'department' => 'required',
            'designation' => 'required',
            'join_date' => 'required',
            'joining_salary' => 'required',
            'salary' => 'required',
            'photo' => 'sometimes|image'
        ]);

        if ($validator->fails()) {
            $request->session()->flash('err', 'Please check the highlighted inputs!');
            return redirect()
                        ->back()
                        ->withErrors($validator)
                        ->withInput();
        }
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public');
            $photo = substr($photo, 7);
        } else{
            $photo = $f_employee->photo;
        }


        $employee = $f_employee->update([
            'name' => $request->name,
            'email' => $request->email,
            'phone' => $request->phone,
            'gender' => $request->gender,
            'dob' => date('Y-m-d', strtotime($request->dob)),
            'present_addr' => $request->present_addr,
            'permanent_addr' => $request->permanent_addr,
            'department' => $request->department,
            'designation' => $request->designation,
            'join_date' => date('Y-m-d', strtotime($request->join_date)),
            'joining_salary' => $request->joining_salary,
            'salary' => $request->salary,
            'father_name' => $request->father_name,
            'photo' => $photo ?? null
        ]);

        if ($employee) {
            $request->session()->flash('msg', 'Employee\'s Information edited Successfully!');
            return redirect()->route('employee.index');
        } else{
            return redirect()->back();
        }

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee = Employee::find($employee)->first();
        $employee->delete();
        return "User deleted Successfully!";
    }
}

resources/views/employees/add.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('err'))
        <div class="alert alert-danger alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i>Error Alert!</h4>
            {{ session('err') }}
        </div>
@endif
<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Add new Employee</h3>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ route('employee.store') }}">
				@csrf
				<div class="box-body">
					<div class="form-group col-sm-3 {{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name">Name</label>
						<input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Enter Name">
						@if ($errors->has('name'))
						<span class="help-block">
							<strong>{{ $errors->first('name') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('email') ? ' has-error' : '' }}">
						<label for="exampleInputEmail1">Email address</label>
						<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') }}">
						@if ($errors->has('email'))
						<span class="help-block">
							<strong>{{ $errors->first('email') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('phone') ? ' has-error' : '' }}">
						<label for="phone">Phone Number</label>
						<input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" value="{{ old('phone') }}">
						@if ($errors->has('phone'))
						<span class="help-block">
							<strong>{{ $errors->first('phone') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('gender') ? ' has-error' : '' }}">
						<label>Gender: </label><br>
						<label>
							<input type="radio" value="m" name="gender" {{ old('gender') == 'm' ? 'checked': '' }}> Male
						</label>
						<label>
							<input type="radio" value="f" name="gender" {{ old('gender') == 'f' ? 'checked': '' }}> Female
						</label>
						@if ($errors->has('gender'))
						<span class="help-block">
							<strong>{{ $errors->first('gender') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('dob') ? ' has-error' : '' }} clearfix">
						<label class="control-label">Date of Birth</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="dob" class="form-control input-sm datepicker" value="{{old('dob')}}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('dob'))
						<span class="help-block">
							<strong>{{ $errors->first('dob') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('present_addr') ? ' has-error' : '' }}">
                        <label>Present Address</label>
                        <textarea name="present_addr" class="form-control input-sm" rows="3">
                        	{{ trim(old('present_addr')) }}
                        </textarea> 
                        @if ($errors->has('present_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('present_addr') }}</strong>
						</span>
						@endif
                    </div>

                    <div class="form-group col-sm-3 {{ $errors->has('permanent_addr') ? ' has-error' : '' }}">
                        <label>Permanent Address</label>
                        <textarea name="permanent_addr" class="form-control input-sm" rows="3">
                        	{{ trim(old('permanent_addr')) }}
                        </textarea>
                        @if ($errors->has('permanent_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('permanent_addr') }}</strong>
						</span>
						@endif
                    </div>
					
					
					<div class="form-group col-sm-3">
						<label>Father Name</label>
						<input type="text" class="form-control" name="father_name" placeholder="Father Name" value="{{ old('father_name') }}">
					</div>


					<div class="form-group col-sm-3 {{ $errors->has('department') ? ' has-error' : '' }} clearfix">
						<label for="Department">Department</label>
						<select name="department" class="form-control">
							<option value="">Select</option>
							<option value="Sales" {{ old('department') == 'Sales' ? 'selected': '' }}>Sales</option>
							<option value="IT" {{ old('department') == 'IT' ? 'selected': '' }}>IT</option>
							<option value="Stock" {{ old('department') == 'Stock' ? 'selected': '' }}>Stock</option>
							<option value="Accounts" {{ old('department') == 'Accounts' ? 'selected': '' }}>Accounts</option>
						</select>
						@if ($errors->has('department'))
						<span class="help-block">
							<strong>{{ $errors->first('department') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('designation') ? ' has-error' : '' }}">
						<label for="designation">Designation</label>
						<select name="designation" class="form-control">
							<option value="">Select</option>
							<option value="CEO" {{ old('designation') == 'CEO' ? 'selected': '' }}>CEO</option>
							<option value="Manager" {{ old('designation') == 'Manager' ? 'selected': '' }}>Manager</option>
							<option value="CFO" {{ old('designation') == 'CFO' ? 'selected': '' }}>CFO</option>
							<option value="Employee" {{ old('designation') == 'Employee' ? 'selected': '' }}>Employee</option>
						</select>
						@if ($errors->has('designation'))
						<span class="help-block">
							<strong>{{ $errors->first('designation') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('joining_salary') ? ' has-error' : '' }}">
						<label for="joining_salary">Joining Salary</label>
						<input type="text" name="joining_salary" class="form-control" placeholder="Enter Joining salary" value="{{ old('joining_salary') }}">
						@if ($errors->has('joining_salary'))
						<span class="help-block">
							<strong>{{ $errors->first('joining_salary') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('salary') ? ' has-error' : '' }}">
						<label for="salary">Salary</label>
						<input type="text" name="salary" class="form-control" placeholder="Enter salary" value="{{ old('salary') }}">
						@if ($errors->has('salary'))
						<span class="help-block">
							<strong>{{ $errors->first('salary') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('join_date') ? ' has-error' : '' }}">
						<label class="control-label">Joining Date</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="join_date" class="form-control input-sm datepicker" value="{{old('join_date')}}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('join_date'))
						<span class="help-block">
							<strong>{{ $errors->first('join_date') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('photo') ? ' has-error' : '' }}">
						<label for="exampleInputFile">Profile Photo</label>
						<input type="file" id="exampleInputFile" name="photo">
						@if ($errors->has('photo'))
						<span class="help-block">
							<strong>{{ $errors->first('photo') }}</strong>
						</span>
						@endif
					</div>
					
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<button type="submit" class="btn btn-primary btn-lg">Submit</button>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/employees/attendance-list.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h1 class="box-title">Attendance List</h1>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example1">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Department</th>
                            <th>Designation</th>
                            <th>Absent Days</th>
                            <th>Off Days</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                            
                    <tbody>
                        @foreach($employees as $employee)
                        <tr>
                            <td>{{ $employee->id }}</td>
                            <td>{{ $employee->name }}</td>
                            <td>{{ $employee->phone }}</td>
                            <td>{{ $employee->department }}</td>
                            <td>{{ $employee->designation }}</td>
                            <td>{{ $employee->count_absent->count }}</td>
                            <td>----</td>
                            <td>----</td>
                            
                        </tr>
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.master')
@section('page_main_content')

@if(session('err'))
        <div class="alert alert-danger alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i>Error Alert!</h4>
            {{ session('err') }}
        </div>
@endif
<div class="row">
	<div class="col-md-12">
		<!-- general form elements -->
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Edit Employee</h3>
			</div>
			<!-- /.box-header -->
			<!-- form start -->
			<form role="form" method="post" enctype="multipart/form-data" action="{{ route('employee.update',['employee' => $employee->id]) }}">
				@method('PUT')
				@csrf
				<div class="box-body">
					<div class="form-group col-sm-3 {{ $errors->has('name') ? ' has-error' : '' }}">
						<label for="name">Name</label>
						<input type="text" name="name" value="{{ $employee->name }}" class="form-control" placeholder="Enter Name">
						@if ($errors->has('name'))
						<span class="help-block">
							<strong>{{ $errors->first('name') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('email') ? ' has-error' : '' }}">
						<label for="exampleInputEmail1">Email address</label>
						<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ $employee->email }}">
						@if ($errors->has('email'))
						<span class="help-block">
							<strong>{{ $errors->first('email') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('phone') ? ' has-error' : '' }}">
						<label for="phone">Phone Number</label>
						<input type="text" name="phone" class="form-control" placeholder="Enter Phone Number" value="{{ $employee->phone }}">
						@if ($errors->has('phone'))
						<span class="help-block">
							<strong>{{ $errors->first('phone') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('gender') ? ' has-error' : '' }}">
						<label>Gender: </label><br>
						<label>
							<input type="radio" value="m" name="gender" {{ $employee->gender == 'm' ? 'checked': '' }}> Male
						</label>
						<label>
							<input type="radio" value="f" name="gender" {{ $employee->gender == 'f' ? 'checked': '' }}> Female
						</label>
						@if ($errors->has('gender'))
						<span class="help-block">
							<strong>{{ $errors->first('gender') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-group col-sm-3 {{ $errors->has('dob') ? ' has-error' : '' }} clearfix">
						<label class="control-label">Date of Birth</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="dob" class="form-control input-sm datepicker" value="{{ $employee->DOB }}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('dob'))
						<span class="help-block">
							<strong>{{ $errors->first('dob') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('present_addr') ? ' has-error' : '' }}">
                        <label>Present Address</label>
                        <textarea name="present_addr" class="form-control input-sm" rows="3">
                        	{{ $employee->present_addr }}
                        </textarea> 
                        @if ($errors->has('present_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('present_addr') }}</strong>
						</span>
						@endif
                    </div>

                    <div class="form-group col-sm-3 {{ $errors->has('permanent_addr') ? ' has-error' : '' }}">
                        <label>Permanent Address</label>
                        <textarea name="permanent_addr" class="form-control input-sm" rows="3">
                        	{{ $employee->permanent_addr }}
                        </textarea>
                        @if ($errors->has('permanent_addr'))
						<span class="help-block">
							<strong>{{ $errors->first('permanent_addr') }}</strong>
						</span>
						@endif
                    </div>
					
					
					<div class="form-group col-sm-3">
						<label>Father Name</label>
						<input type="text" class="form-control" name="father_name" placeholder="Father Name" value="{{ $employee->father_name }}">
					</div>


					<div class="form-group col-sm-3 {{ $errors->has('department') ? ' has-error' : '' }} clearfix">
						<label for="Department">Department</label>
						<select name="department" class="form-control">
							<option value="">Select</option>
							<option value="Sales" {{ $employee->department == 'Sales' ? 'selected': '' }}>Sales</option>
							<option value="IT" {{ $employee->department == 'IT' ? 'selected': '' }}>IT</option>
							<option value="Stock" {{ $employee->department == 'Stock' ? 'selected': '' }}>Stock</option>
							<option value="Accounts" {{ $employee->department == 'Accounts' ? 'selected': '' }}>Accounts</option>
						</select>
						@if ($errors->has('department'))
						<span class="help-block">
							<strong>{{ $errors->first('department') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('designation') ? ' has-error' : '' }}">
						<label for="designation">Designation</label>
						<select name="designation" class="form-control">
							<option value="">Select</option>
							<option value="CEO" {{ $employee->designation == 'CEO' ? 'selected': '' }}>CEO</option>
							<option value="Manager" {{ $employee->designation == 'Manager' ? 'selected': '' }}>Manager</option>
							<option value="CFO" {{ $employee->designation == 'CFO' ? 'selected': '' }}>CFO</option>
							<option value="Employee" {{ $employee->designation == 'Employee' ? 'selected': '' }}>Employee</option>
						</select>
						@if ($errors->has('designation'))
						<span class="help-block">
							<strong>{{ $errors->first('designation') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('joining_salary') ? ' has-error' : '' }}">
						<label for="joining_salary">Joining Salary</label>
						<input type="text" name="joining_salary" class="form-control" placeholder="Enter Joining salary" value="{{ $employee->joining_salary }}">
						@if ($errors->has('joining_salary'))
						<span class="help-block">
							<strong>{{ $errors->first('joining_salary') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('salary') ? ' has-error' : '' }}">
						<label for="salary">Salary</label>
						<input type="text" name="salary" class="form-control" placeholder="Enter salary" value="{{ $employee->salary }}">
						@if ($errors->has('salary'))
						<span class="help-block">
							<strong>{{ $errors->first('salary') }}</strong>
						</span>
						@endif
					</div>

					<div class="form-group col-sm-3 {{ $errors->has('join_date') ? ' has-error' : '' }}">
						<label class="control-label">Joining Date</label>
						<div class="input-group col-md-12">
							<div class="input-group-addon">
								<i class="fa fa-calendar"></i>
							</div>
							<input type="text" name="join_date" class="form-control input-sm datepicker" value="{{$employee->join_date }}" placeholder="Date of Birth">
						</div>
						@if ($errors->has('join_date'))
						<span class="help-block">
							<strong>{{ $errors->first('join_date') }}</strong>
						</span>
						@endif
					</div>
				@if($employee->photo == NULL)
					<div class="form-group col-sm-3 {{ $errors->has('photo') ? ' has-error' : '' }}">
						<label for="exampleInputFile">Profile Photo</label>
						<input type="file" id="exampleInputFile" name="photo">
						@if ($errors->has('photo'))
						<span class="help-block">
							<strong>{{ $errors->first('photo') }}</strong>
						</span>
						@endif
					</div>
				@endif
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<button type="submit" class="btn btn-primary btn-lg">Submit</button>
				</div>
			</form>
		</div>
		<!-- /.box -->
	</div>
</div>
@endsection

resources/views/employees/employee-list.blade.php
@extends('layouts.master')
@section('page_main_content')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">Employees</h3>
        <a href="{{ route('employee.create') }}" class="text-right btn btn-success"><i class="fa fa-users fa-fw"></i> Add Employee</a>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <!-- /.box-header -->
        <div class="box-body">
            <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <table id="example1" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example1_info">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Department</th>
                            <th>Designation</th>
                            <th>Joining Date</th>
                            <th>Joining Salary</th>
                            <th>Current Salary</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                            
                    <tbody>
                        @foreach($employees as $employee)
                        <tr>
                            <td>{{ $employee->id }}</td>
                            <td>{{ $employee->name }}</td>
                            <td>{{ $employee->email }}</td>
                            <td>{{ $employee->phone }}</td>
                            <td>{{ $employee->department }}</td>
                            <td>{{ $employee->designation }}</td>
                            <td>{{ $employee->join_date }}</td>
                            <td>{{ $employee->joining_salary }}</td>
                            <td>{{ $employee->salary }}</td>
                            <td>
                                <a href="{{ route('employee.show', ['employee' => $employee->id ]) }}" class="btn btn-info">
                                    <i class="fa fa-user"></i> 
                                </a>
                                <a href="{{ route('employee.edit',['employee' => $employee->id]) }}" class="btn btn-warning">
                                    <i class="fa fa-edit"></i> 
                                </a>
                                
                                <a href="javascript;" class="btn btn-danger" @click.prevent="deleteEmployee({{ $employee->id }})">
                                    <i class="fa fa-trash"></i> 
                                </a>
                            </td>
                            
                        </tr>
                        @endforeach
                    </tbody>
                            
                </table>
            </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
</div>
@endsection

resources/views/employees/take-attendance.blade.php
@extends('layouts.master')
@section('style')
<style type="text/css">

</style>
@endsection
@section('page_main_content')
<div class="box">
    <div class="box-header">
        <h1 class="box-title">Take Attendance of today <strong> ({{ date("F j, Y") }})</strong></h1>
        <a href="{{ route('attendance.index') }}" class="text-right btn btn-info pull-right"><i class="fa fa-book fa-fw"></i> View Attendance List</a>
    </div>

@if(session('msg'))
        <div class="alert alert-success alert-dismissible notify">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i>Success Alert!</h4>
            {{ session('msg') }}
        </div>
@endif

<attendance></attendance>
</div>
@endsection